### ISSUE TITLE
Incorrect path for grub configuration file

### ISSUE THREAD

**Issue by huwan** [zainryan/INSIDER-System#2]
The path for grub2 configuration file in README.md seems incorrect.
```
sudo grub2-mkconfig -o /boot/grub/grub.conf
```
According to the offical wiki [Setting Up grub2 on CentOS 7](https://wiki.centos.org/HowTos/Grub2), the correct path seems to be `/boot/grub2/grub.cfg`.
```
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
```
This problem also exists in the prebuilt AWS image.

**Comment by zainryan** [comment]
Thanks!
